/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,jsx}',
    './src/components/**/*.{js,jsx}',
    './src/app/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e5e2e1",
        "surface-tint": "#fbbc00",
        "secondary-fixed-dim": "#c8c6c5",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#6d5000",
        "surface-container": "#1a1a1a",
        "surface-bright": "#3a3939",
        "surface": "#0A0A0A",
        "outline": "#9c8f78",
        "inverse-surface": "#e5e2e1",
        "surface-container-high": "#222222",
        "on-secondary-fixed": "#1c1b1b",
        "tertiary-container": "#cbc9c8",
        "secondary": "#c8c6c5",
        "on-background": "#e5e2e1",
        "on-secondary": "#313030",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "tertiary": "#e8e5e4",
        "on-primary-fixed-variant": "#5c4300",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#474746",
        "on-tertiary-container": "#555454",
        "primary-fixed": "#ffdfa0",
        "primary-fixed-dim": "#fbbc00",
        "background": "#0A0A0A",
        "on-surface-variant": "#d4c5ab",
        "on-primary-fixed": "#261a00",
        "tertiary-fixed": "#e4e2e1",
        "on-tertiary-fixed-variant": "#474746",
        "inverse-primary": "#795900",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "on-secondary-container": "#b7b5b4",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container-low": "#111111",
        "on-primary": "#402d00",
        "inverse-on-surface": "#313030",
        "primary": "#FFBF00",
        "surface-container-lowest": "#050505",
        "on-tertiary": "#303030",
        "outline-variant": "#333333",
        "secondary-container": "#474746",
        "primary-container": "#FFBF00",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        // Keeping some functional names if needed, but mapped to the new palette
        border: '#1c1c1c',
        input: '#1a1a1a',
        ring: '#FFBF00',
        foreground: '#e5e2e1',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "32px",
        "gutter": "48px",
        "margin-page": "64px",
        "stack-sm": "8px",
        "unit": "8px",
        "section-gap": "80px",
        "stack-md": "16px"
      },
      fontFamily: {
        "label-md": ["var(--font-manrope)"],
        "body-md": ["var(--font-manrope)"],
        "headline-lg": ["var(--font-epilogue)"],
        "body-lg": ["var(--font-manrope)"],
        "headline-md": ["var(--font-epilogue)"],
        "label-sm": ["var(--font-manrope)"],
        "display-xl": ["var(--font-epilogue)"],
        "epilogue": ["var(--font-epilogue)"],
        "manrope": ["var(--font-manrope)"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "display-xl": ["72px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}